name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Install CodePush CLI
      run: npm install -g code-push-cli

    - name: Print ESLint Version
      run: npx eslint --version

    - name: Print ESLint Configuration
      run: npx eslint --print-config .eslintrc.js

    - name: Lint
      run: npx eslint .

    - name: Deploy to CodePush
      env:
        APP_NAME: 'YourAppName'
        CODEPUSH_ACCESS_KEY: ${{ secrets.CODEPUSH_ACCESS_KEY }}
      run: |
        set -x
        code-push release-react $APP_NAME android -d Production -k $CODEPUSH_ACCESS_KEY || exit 1

    - name: Notify Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          curl -X POST -H 'Content-type: application/json' --data '{"text":"✅ CI/CD Pipeline succeeded for React Native project."}' $SLACK_WEBHOOK_URL
        else
          curl -X POST -H 'Content-type: application/json' --data '{"text":"❌ CI/CD Pipeline failed for React Native project."}' $SLACK_WEBHOOK_URL
        fi
