name: Build Android
on:
  push:
     branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

   - name: Build Android app Release
      run: cd android && ./gradlew assembleRelease

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: android/app/build/outputs/apk/release/app-release.apk
